### ISSUE TITLE
SACK == ACK bug

### ISSUE THREAD

**Issue by Razvi99** [yasukata/iip#2]
Hey, discovered a bug:

```
if (p->tcp.opt.sack_opt_off) {
    __iip_enqueue_obj(conn->tcp_sack_rx, p, 0);
    if (!(conn->flags & __IIP_TCP_CONN_FLAGS_PEER_RX_FAILED)) {
        IIP_OPS_DEBUG_PRINTF("loss detected (sack) : %p seq %u ack %u\n", (void *) conn, __iip_ntohl(conn->seq_be), __iip_ntohl(conn->ack_seq_be));
        conn->cc.ssthresh = (conn->cc.win / 2 < 1 ? 2 : conn->cc.win / 2);
        conn->cc.win = conn->cc.ssthresh;
        __iip_assert(conn->head[2][0] && conn->head[2][1]);
```

the last assert fails, because everything we sent was already ACKED, but the packet also contains a SACK, so iip thinks this is rx loss without checking, but ` conn->head[2][0] ` is null.

In my limited knowledge, you can just check if all data is already acked and not declare rx loss. Do you have another solution that is better?

I attached the pcap. The code fails on the last packet.

[output.pcap.zip](https://github.com/user-attachments/files/17662614/output.pcap.zip)

Have a good day

**Comment by yasukata** [comment]
Thank you for your message.

> the last assert fails, because everything we sent was already ACKED, but the packet also contains a SACK, so iip thinks this is rx loss without checking, but conn->head[2][0] is null.

I have not been aware of this case, and the implementation has not considered it.

> you can just check if all data is already acked and not declare rx loss.

Thank you for your suggestion. I believe your idea works, and I have updated the program in https://github.com/yasukata/iip/commit/3ff62fe6d543036ade4d6db3d5dcb9e9e92feecf .

Thank you very much for your detailed report and suggestion.

**Comment by Razvi99** [comment]
Thanks!
